### ISSUE TITLE
Error when opening gui in 4-core codespace

### ISSUE THREAD

**Issue by Adam-Albu** [XingangPan/DragGAN#109]
I cloned this repo in a codespace using 32GB ram and 4 cores. I then I pre-trained the weights and installed the requirements. Then when I tried opening the GUI, this error occured:
```
Traceback (most recent call last):
  File "/workspaces/DragGAN/visualizer_drag.py", line 17, in <module>
    from gui_utils import imgui_window
  File "/workspaces/DragGAN/gui_utils/imgui_window.py", line 11, in <module>
    import imgui.integrations.glfw
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/imgui/integrations/glfw.py", line 8, in <module>
    from .opengl import ProgrammablePipelineRenderer
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/imgui/integrations/opengl.py", line 4, in <module>
    import OpenGL.GL as gl
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

**Comment by MittalNeha** [comment]
I am seeing the same error. Please share in case you find a solution.

**Comment by Jianghaob** [comment]
I am seeing the same error too

**Comment by xxyyboy** [comment]
I am seeing the same error too

**Comment by YangJay99** [comment]
I met the same problem and solved it, it is the pyopengl problem.
I downgraded the pyopengl : pip install pyopengl .
and then install python3-opengl package by apt-get:  sudo apt-get install python3-opengl
https://github.com/MPI-IS/mesh/issues/23
