### ISSUE TITLE
WSL2 error trying to open pkl when start

### ISSUE THREAD

**Issue by darthzulder** [XingangPan/DragGAN#134]
I have the next error running sh scripts/gui.sh in WSL2 and conda.

"... Failed!t/e/StableDussion/GitBash/DragGAN/

Traceback (most recent call last):
  File "/mnt/e/StableDussion/GitBash/DragGAN/viz/renderer.py", line 138, in get_network
    with dnnlib.util.open_url(pkl, verbose=False) as f:
  File "/mnt/e/StableDussion/GitBash/DragGAN/dnnlib/util.py", line 403, in open_url
    return url if return_filename else open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/e/StableDussion/GitBash/DragGAN/\r'

**Comment by fruitswordman** [comment]
Same issue when initiating on windows using conda, with all checkpoint files installed already.

**Comment by pxcai** [comment]
Did you solve the problem?

**Comment by mandolin** [comment]
edit gui.sh, change it to a siingle line

`
python visualizer_drag.py checkpoints/stylegan2_lions_512_pytorch.pkl checkpoints/stylegan2-ffhq-512x512.pkl checkpoints/stylegan2-afhqcat-512x512.pkl checkpoints/stylegan2-car-config-f.pkl checkpoints/stylegan2_dogs_1024_pytorch.pkl checkpoints/stylegan2_horses_256_pytorch.pkl checkpoints/stylegan2-cat-config-f.pkl checkpoints/stylegan2_elephants_512_pytorch.pkl checkpoints/stylegan_human_v2_512.pkl checkpoints/stylegan2-lhq-256x256.pkl
`
