### ISSUE TITLE
when try to drug picture to app have such msg

### ISSUE THREAD

**Issue by alanhk147** [XingangPan/DragGAN#138]
D:\AI_TOOLS\DYGAN\DragGAN>D:/AI_TOOLS/MUSIC/audiocraft/python_3_9/python D:\AI_TOOLS\DYGAN\DragGAN\visualizer_drag.py
Loading "C:\Users\Alex\Pictures\Screenshot.jpg"... Failed!

Traceback (most recent call last):
  File "D:\AI_TOOLS\DYGAN\DragGAN\viz\renderer.py", line 139, in get_network
    data = legacy.load_network_pkl(f)
  File "D:\AI_TOOLS\DYGAN\DragGAN\legacy.py", line 23, in load_network_pkl
    data = _LegacyUnpickler(f).load()
_pickle.UnpicklingError: invalid load key, '\xff'.

**Comment by alanhk147** [comment]
all checkpoints already placed in ./checkpoints

**Comment by IssacCzy** [comment]
I had the same problem
