### ISSUE TITLE
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

### ISSUE THREAD

**Issue by so349mng** [XingangPan/DragGAN#152]
When executing py file,
`   !python /content/DragGAN/visualizer_drag_gradio.py`

File under cache_dir (./checkpoints):
['stylegan2_horses_256_pytorch.pkl', 'stylegan2_elephants_512_pytorch.pkl', 'stylegan2-ffhq-512x512.pkl', 'stylegan2_lions_512_pytorch.pkl', 'stylegan2_dogs_1024_pytorch.pkl', 'stylegan2-afhqcat-512x512.pkl', 'stylegan2-cat-config-f.pkl', 'stylegan2-car-config-f.pkl']
Valid checkpoint file:
{'stylegan2_horses_256_pytorch': './checkpoints/stylegan2_horses_256_pytorch.pkl', 'stylegan2_elephants_512_pytorch': './checkpoints/stylegan2_elephants_512_pytorch.pkl', 'stylegan2-ffhq-512x512': './checkpoints/stylegan2-ffhq-512x512.pkl', 'stylegan2_lions_512_pytorch': './checkpoints/stylegan2_lions_512_pytorch.pkl', 'stylegan2_dogs_1024_pytorch': './checkpoints/stylegan2_dogs_1024_pytorch.pkl', 'stylegan2-afhqcat-512x512': './checkpoints/stylegan2-afhqcat-512x512.pkl', 'stylegan2-cat-config-f': './checkpoints/stylegan2-cat-config-f.pkl', 'stylegan2-car-config-f': './checkpoints/stylegan2-car-config-f.pkl'}
Loading "./checkpoints/stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.

**Traceback (most recent call last):**
  File "/content/DragGAN/visualizer_drag_gradio.py", line 205, in <module>
    global_state = init_images(global_state)
  File "/content/DragGAN/visualizer_drag_gradio.py", line 96, in init_images
    add_watermark_np(np.array(init_image)))
  File "/content/DragGAN/viz/renderer.py", line 56, in add_watermark_np
    text_width, text_height = font.getsize(watermark_text)
**AttributeError: 'FreeTypeFont' object has no attribute 'getsize'**

**Comment by marianbastiUNRN** [comment]
You can nasty-fix it by replacing on line 56 in viz.renderer:
```
text_width, text_height = [0,0]
```

**Comment by cobanov** [comment]
Solved on this PR  #239

**Comment by radames** [comment]
hi @cobanov you can pin `Pillow==9.5.0`, it seems to be an issue with the newest `Pillow==10.0.0`

**Comment by so349mng** [comment]
Thank for all your guys.
It works.   !!!

[image: 截屏2023-07-16 14.47.44.png]

Radamés Ajna ***@***.***> 于2023年7月4日周二 23:43写道：
