### ISSUE TITLE
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in 

### ISSUE THREAD

**Issue by xinmans** [XingangPan/DragGAN#309]
Traceback (most recent call last):
  File "C:\Users\xinmans\DragGAN\viz\renderer.py", line 112, in render
    self.init_network(res, **args)
  File "C:\Users\xinmans\DragGAN\viz\renderer.py", line 249, in init_network
    w = G.mapping(z, label, truncation_psi=trunc_psi, truncation_cutoff=trunc_cutoff)
  File "C:\ProgramData\Anaconda3\envs\stylegan3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xinmans\DragGAN\training\networks_stylegan2.py", line 247, in forward
    x = layer(x)
  File "C:\ProgramData\Anaconda3\envs\stylegan3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xinmans\DragGAN\training\networks_stylegan2.py", line 125, in forward
    x = bias_act.bias_act(x, b, act=self.activation)
  File "C:\Users\xinmans\DragGAN\torch_utils\ops\bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "C:\Users\xinmans\DragGAN\torch_utils\ops\bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
  File "C:\Users\xinmans\DragGAN\torch_utils\custom_ops.py", line 84, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "C:\Users\xinmans\DragGAN\torch_utils\custom_ops.py".

Loading "C:\Users\xinmans\DragGAN\checkpoints\stylegan2-car-config-f.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu', 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}}
Setting up PyTorch plugin "bias_act_plugin"... Failed!
Loading "C:\Users\xinmans\DragGAN\checkpoints\stylegan2-ffhq-512x512.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': 512, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'channel_base': 32768, 'channel_max': 512, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}
Setting up PyTorch plugin "bias_act_plugin"... Failed!

**Comment by gocreater** [comment]
修改 torch_utils目录下的custom_ops.py文件第31行内容，将Professional更换成*（默认为专业版，如有多个版本请指定一个版Microsoft Visual Studio版本）。

Modify the 31st line of the custom.py file in the torch_utils directory and replace Professional with * (default to Professional version, if there are multiple versions, please specify one version of Microsoft Visual Studio).

**Comment by Vadim2S** [comment]
Small explanation. There ugly antipattern hard-coded path strings in torch_utils/custom_ops.py/_find_compiler_bindir() like
``
'C:/Program Files*/Microsoft Visual Studio/*/Professional/VC/Tools/MSVC/*/bin/Hostx64/x64',
``
and of course this do not work if you use another Visual Studio version or install it somewhere else in different folder.
Change there paths and all OK.

**Comment by christopherquenneville** [comment]
- Download Visual Studio
	https://visualstudio.microsoft.com/downloads/
	After downloading the installer, install community edition and make sure to download the latest MSVC ##and the latest c++ (14.x or later)
	The program is looking for compilers in "C:/Program Files*/Microsoft Visual Studio/*/Community/VC/Tools/MSVC/*/bin/Hostx64/x64"
- Download Visual Studio Build Tools
	Use same previous installer to download Visual Studio Build Tools and make sure to download the "desktop development with c++" package

**Comment by hitzhangjie** [comment]
I install gcc-g++ by Cygwin, and add the path to custom_opts.py, when I start DragGAN by scripts\gui.bat.

Now it reports cl.exe is not found, which is provided by Visual Studio 2022, but I want didn't install it and I expect to use the GCC.

Do I need to install the Visual Studio 2022?

**Comment by Vadim2S** [comment]
About using GCC/CLANG instead MSVC. I am not check it but try change torch_utils/custom_ops.py/_find_compiler_bindir() function. This quite strightforward and simple. Just provide path to you compiler.

**Comment by AndrewZion** [comment]
RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{file}"
**solution**
在torch_utils中的custom_ops.py文件中第31行修改为自己visual studio的编译器路径，将作者的路径注释掉，像以下这样
Modify line 31 in the custom_ops.py file in torch_utils to the compiler path of your visual studio, and comment out the author's path, like the following

```
patterns = [
        'D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64'
        # 'C:/Program Files*/Microsoft Visual Studio/*/Professional/VC/Tools/MSVC/*/bin/Hostx64/x64',
        # 'C:/Program Files*/Microsoft Visual Studio/*/BuildTools/VC/Tools/MSVC/*/bin/Hostx64/x64',
        # 'C:/Program Files*/Microsoft Visual Studio/*/Community/VC/Tools/MSVC/*/bin/Hostx64/x64',
        # 'C:/Program Files*/Microsoft Visual Studio */vc/bin',
    ]
```
