### ISSUE TITLE
RuntimeError: "slow_conv_transpose2d_out_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by T9es** [XingangPan/DragGAN#317]
```
Traceback (most recent call last):
  File "Y:\AI-GIT-CLONE\DragGAN\viz\renderer.py", line 113, in render
    self._render_drag_impl(res, **args)
  File "Y:\AI-GIT-CLONE\DragGAN\viz\renderer.py", line 311, in _render_drag_impl
    img, feat = G(ws, label, truncation_psi=trunc_psi, noise_mode=noise_mode, input_is_w=True, return_feature=True)
  File "C:\Users\XD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "Y:\AI-GIT-CLONE\DragGAN\stylegan_human\training_scripts\sg2\training\networks.py", line 539, in forward
    img = self.synthesis(ws, return_feature=return_feature, **synthesis_kwargs)
  File "C:\Users\XD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "Y:\AI-GIT-CLONE\DragGAN\stylegan_human\training_scripts\sg2\training\networks.py", line 498, in forward
    x, img = block(x, img, cur_ws, **block_kwargs)
  File "C:\Users\XD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "Y:\AI-GIT-CLONE\DragGAN\stylegan_human\training_scripts\sg2\training\networks.py", line 426, in forward
    x = self.conv0(x, next(w_iter), fused_modconv=fused_modconv, **layer_kwargs)
  File "C:\Users\XD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "Y:\AI-GIT-CLONE\DragGAN\stylegan_human\training_scripts\sg2\training\networks.py", line 312, in forward
    x = modulated_conv2d(x=x, weight=self.weight, styles=styles, noise=noise, up=self.up,
  File "Y:\AI-GIT-CLONE\DragGAN\torch_utils\misc.py", line 103, in decorator
    return fn(*args, **kwargs)
  File "Y:\AI-GIT-CLONE\DragGAN\stylegan_human\training_scripts\sg2\training\networks.py", line 67, in modulated_conv2d
    x = conv2d_resample.conv2d_resample(x=x, w=weight.to(x.dtype), f=resample_filter, up=up, down=down, padding=padding, flip_weight=flip_weight)
  File "Y:\AI-GIT-CLONE\DragGAN\torch_utils\misc.py", line 103, in decorator
    return fn(*args, **kwargs)
  File "Y:\AI-GIT-CLONE\DragGAN\torch_utils\ops\conv2d_resample.py", line 125, in conv2d_resample
    x = _conv2d_wrapper(x=x, w=w, stride=up, padding=[pyt,pxt], groups=groups, transpose=True, flip_weight=(not flip_weight))
  File "Y:\AI-GIT-CLONE\DragGAN\torch_utils\ops\conv2d_resample.py", line 41, in _conv2d_wrapper
    return op(x, w, stride=stride, padding=padding, groups=groups)
  File "Y:\AI-GIT-CLONE\DragGAN\torch_utils\ops\conv2d_gradfix.py", line 43, in conv_transpose2d
    return torch.nn.functional.conv_transpose2d(input=input, weight=weight, bias=bias, stride=stride, padding=padding, output_padding=output_padding, groups=groups, dilation=dilation)
RuntimeError: "slow_conv_transpose2d_out_cpu" not implemented for 'Half'
```

After trying to load the human model. (The same machine is running stable diffusion, might be a cuda related issue?)

**Comment by cannacak** [comment]
I encountered the same issue, still no solution ?

**Comment by T9es** [comment]
Sadly no, can't try out things on my own due to how bad my internet currently is. Downloading CUDA would take a dozen hours

**Comment by T9es** [comment]
Sadly no, can't try out things on my own due to how bad my internet currently is. Downloading CUDA would take a dozen hours

**Comment by T9es** [comment]
Sadly no, can't try out things on my own due to how bad my internet currently is. Downloading CUDA would take a dozen hours

**Comment by T9es** [comment]
I had issues with running it first, had to disable `self._start_event` and `self._end_event`. After that, the GUI started working (Before this, it would close out instantly). Tried loading a model, but that's the error I get. I don't think I'm trying to run it on CPU, although the recomended vram is 12 (I have 1x RTX3060ti, and 1x RTX2060, so the max is 8gb on one card). My current CPU is a R7 5700X

Listing the packages will be hard, as there are over 900 (If we are talking about site packages.). The only thing that used CUDA or Torch in the past is Stable Diffusion.

Yeah, I also went through that github repo, multiple of them to be exact, but I can't seem to find any issue locally.

**Comment by PDillis** [comment]
Sorry, what do you mean you have over 900? You didn't create a new one with the `environment.yml`? If you didn't, try now by first creating it with [conda](https://docs.conda.io/en/latest/miniconda.html) via `conda create -f environment.yml`. This way you can contain environments for specific projects. For example, this is the list of my env packages for all things StyleGAN2-ADA and up (on a Windows laptop w/a GTX 980m):

```
(stylegan3) C:\Users\Diego>pip list
Package                      Version
---------------------------- ---------
absl-py                      1.0.0
astunparse                   1.6.3
attrs                        22.1.0
brotlipy                     0.7.0
cachetools                   5.0.0
certifi                      2021.10.8
cffi                         1.15.0
charset-normalizer           2.0.12
click                        8.1.2
clip                         1.0
colorama                     0.4.4
cryptography                 36.0.2
cycler                       0.11.0
decorator                    4.4.2
einops                       0.6.1
ffmpeg-python                0.2.0
flatbuffers                  23.3.3
ftfy                         6.1.1
future                       0.18.2
gast                         0.4.0
glfw                         2.2.0
google-auth                  2.6.3
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.44.0
h5py                         3.8.0
idna                         3.3
imageio                      2.9.0
imageio-ffmpeg               0.4.3
imgui                        1.3.0
importlib-metadata           4.11.3
imutils                      0.5.4
joblib                       1.1.0
keras                        2.11.0
kiwisolver                   1.4.2
libclang                     15.0.6.1
Markdown                     3.3.6
matplotlib                   3.4.2
mediapipe                    0.8.11
moviepy                      1.0.3
numpy                        1.22.3
oauthlib                     3.2.0
olefile                      0.46
opencv-contrib-python        4.6.0.66
opencv-python                4.6.0.66
opt-einsum                   3.3.0
packaging                    23.0
perlin-numpy                 0.0.0
Pillow                       9.1.0
pip                          22.0.4
proglog                      0.1.9
protobuf                     3.19.6
psutil                       5.9.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
PyAudio                      0.2.12
pycparser                    2.21
PyOpenGL                     3.1.5
pyOpenSSL                    22.0.0
pyparsing                    3.0.8
pyperlin                     1.1.0
PyQt5                        5.12.3
PyQt5_sip                    4.19.18
PyQtChart                    5.12
PyQtWebEngine                5.12.1
PySocks                      1.7.1
pyspng                       0.1.0
python-dateutil              2.8.2
PyYAML                       6.0
regex                        2022.4.24
requests                     2.26.0
requests-oauthlib            1.3.1
rsa                          4.8
scikit-learn                 1.1.2
scikit-video                 1.1.11
scipy                        1.7.1
setuptools                   61.2.0
six                          1.16.0
sklearn                      0.0
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-estimator         2.11.0
tensorflow-intel             2.11.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.2.0
threadpoolctl                3.1.0
torch                        1.11.0
torchaudio                   0.11.0
torchvision                  0.12.0
tornado                      6.1
tqdm                         4.62.2
ttach                        0.0.3
typing_extensions            4.1.1
urllib3                      1.26.9
wcwidth                      0.2.5
Werkzeug                     2.1.1
wheel                        0.37.1
win-inet-pton                1.1.0
wincertstore                 0.2
wrapt                        1.15.0
zipp                         3.8.0
```

It does seem that your setup is using the CPU. You can print which device you're using to get rid of any doubts, but I'm almost certain of this. Creating a new `env` is most likely the easiest solution out of this IMO, otherwise, you'll have conflicting packages.
