### ISSUE TITLE
Trying to run on Mac m1

### ISSUE THREAD

**Issue by Pawandeep-prog** [XingangPan/DragGAN#32]
My Mac configs:
os: Mac OS 13.4 (22F66)
cpu: Mac m1
ram: 8GB

after running through 
`sh scripts/gui.sh`

I am getting segment fault:
`scripts/gui.sh: line 2: 77912 Segmentation fault: 11  python visualizer_drag.py checkpoints/stylegan2_lions_512_pytorch.pkl`

need any more information would be happy to share.

**Comment by Pawandeep-prog** [comment]
after further tracking the code,

found that the fault is due to this line

`self.set_window_size(window_width, window_height)`

from `gui_utils/glfw_window.py` in the __init__() function.

**Comment by Pawandeep-prog** [comment]
okay resolved segmentation fault

it was due to 
`self.monitor_height` and `self.monitor_width` variables
in the same file `def set_window_size(self, width, height):` this function

I removed them and hard coded 1920 and 1080 instead.

**Comment by Pawandeep-prog** [comment]
Getting this error

```
Traceback (most recent call last):
  File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/visualizer_drag.py", line 404, in <module>
    main()
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/visualizer_drag.py", line 363, in main
    viz = Visualizer(capture_dir=capture_dir)
  File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/visualizer_drag.py", line 31, in __init__
    super().__init__(title='DragGAN', window_width=3840, window_height=2160)
  File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/gui_utils/imgui_window.py", line 43, in __init__
    self._imgui_renderer = _GlfwRenderer(self._glfw_window)
  File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/gui_utils/imgui_window.py", line 102, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/imgui/integrations/glfw.py", line 12, in __init__
    super(GlfwRenderer, self).__init__()
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/imgui/integrations/opengl.py", line 60, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/imgui/integrations/base.py", line 17, in __init__
    self._create_device_objects()
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/imgui/integrations/opengl.py", line 108, in _create_device_objects
    self._attrib_location_tex = gl.glGetUniformLocation(self._shader_handle, "Texture")
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (1, b'Texture\x00'),
	result = -1
)
```

any help would be appreciated :)

**Comment by albusdemens** [comment]
> Getting this error
> 
> ```
> Traceback (most recent call last):
>   File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/visualizer_drag.py", line 404, in <module>
>     main()
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/visualizer_drag.py", line 363, in main
>     viz = Visualizer(capture_dir=capture_dir)
>   File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/visualizer_drag.py", line 31, in __init__
>     super().__init__(title='DragGAN', window_width=3840, window_height=2160)
>   File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/gui_utils/imgui_window.py", line 43, in __init__
>     self._imgui_renderer = _GlfwRenderer(self._glfw_window)
>   File "/Users/pawandeepsingh/Documents/Development/official_draggan/DragGAN/gui_utils/imgui_window.py", line 102, in __init__
>     super().__init__(*args, **kwargs)
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/imgui/integrations/glfw.py", line 12, in __init__
>     super(GlfwRenderer, self).__init__()
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/imgui/integrations/opengl.py", line 60, in __init__
>     super(ProgrammablePipelineRenderer, self).__init__()
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/imgui/integrations/base.py", line 17, in __init__
>     self._create_device_objects()
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/imgui/integrations/opengl.py", line 108, in _create_device_objects
>     self._attrib_location_tex = gl.glGetUniformLocation(self._shader_handle, "Texture")
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/OpenGL/latebind.py", line 63, in __call__
>     return self.wrapperFunction( self.baseFunction, *args, **named )
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
>     return baseOperation( program, name )
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
>     return self( *args, **named )
>   File "/Users/pawandeepsingh/miniforge3/lib/python3.9/site-packages/OpenGL/error.py", line 230, in glCheckError
>     raise self._errorClass(
> OpenGL.error.GLError: GLError(
> 	err = 1282,
> 	description = b'invalid operation',
> 	baseOperation = glGetUniformLocation,
> 	cArguments = (1, b'Texture\x00'),
> 	result = -1
> )
> ```
> 
> any help would be appreciated :)

I got the same error message after installing the repo on Linux using WSL.

**Comment by albusdemens** [comment]
@Pawandeep-prog I fixed the issue by following [this suggestion](https://github.com/NVlabs/stylegan3/issues/66#issuecomment-1006375618).

**Comment by Pawandeep-prog** [comment]
I think it require cuda to run as I see in stylegan3 repo, and I am running Mac m1 maybe that is the issue. :(

**Comment by iWooda** [comment]
MacOS  
M1

`scripts/gui.sh: line 1: python: command not found`
Line 1  😭

**Comment by aBner6667** [comment]
Expecting value: line 1 column 1 (char 0), 新手，第一次打开web想使用就弹出来这个。

**Comment by alex-calderwood** [comment]
@albusdemens when you say fixed, do you mean the project was running?

**Comment by oscarmore2** [comment]
I track my issue, I found the problem is caused by : ```_, _, _width, height = glfw.get_monitor_workarea(glfw.get_primary_monitor())```, in ```glfw_window.py```, line 82. 
My macbook pro is MacOS Monterey 2021, M1 pro chip.
It return a null pointer while it tried to query the monitor size, but fail
It seems like the glfw library didn't have good support in arm chip. Maybe using Metal could resolve it?

**Comment by Pawandeep-prog** [comment]
I also had problem over there, didn't found any solution so I hard coded these values. :(

**Comment by siyun-liang** [comment]
I try:
```python
        glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 3)
        glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
        glfw.window_hint(glfw.OPENGL_FORWARD_COMPAT, glfw.TRUE)
        glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)
```
        
I want to set the openGL context to 3.3, while:
        version = gl.glGetString(gl.GL_VERSION)
        print("OpenGL Version:", version)
prints OpenGL Version: b'4.1 Metal - 83.1'. (without the change it prints 2.1 Metal)

With this change:
`self._imgui_renderer = _GlfwRenderer(self._glfw_window)`
in line 40, imgui_window.py throws no exception.

But further exception was thrown: gui_utils/glfw_window.py", line 193, in begin_frame
```
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glMatrixMode,
	cArguments = (GL_PROJECTION,)
)
```

**Comment by ucodia** [comment]
I have spent a fair amount of time debugging this issue and concluded that the codebase cannot run on macOS without a significant refactoring of the OpenGL code.

The OpenGL code in `visualizer.py` and `gl_utils.py` uses APIs that were released after OpenGL 2.1 and fixed function pipeline API (for example `glMatrixMode`). macOS has a known issue with that, specifically it cannot mix legacy functions with newer 3.2+ functions. This is mentioned in the official OpenGL wiki:

> Platform Issue (MacOSX): When MacOSX 10.7 introduced support for OpenGL beyond 2.1, they also introduced the core/compatibility dichotomy. However, they did not introduce support for the compatibility profile itself. Instead, MacOSX gives you a choice: core profile for versions 3.2 or higher, or just version 2.1. There is no way to get access to features after 2.1 and still access the [Fixed Function Pipeline](https://www.khronos.org/opengl/wiki/Fixed_Function_Pipeline).

See https://www.khronos.org/opengl/wiki/OpenGL_Context#OpenGL_3.2_and_Profiles

The only path forward to make this work on macOS is to migrate code which uses the fixed function pipeline to use shader-based programming instead.
