### ISSUE TITLE
Attribute Error: image

### ISSUE THREAD

**Issue by alimehdi242** [XingangPan/DragGAN#38]
Traceback (most recent call last):
  File "C:\Users\alime\Downloads\DragGAN-main1\DragGAN-main\dnnlib\util.py", line 45, in __getattr__
    return self[name]
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alime\Downloads\DragGAN-main1\DragGAN-main\visualizer_drag.py", line 402, in <module>
    main()
  File "C:\Users\alime\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\alime\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\alime\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\alime\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\alime\Downloads\DragGAN-main1\DragGAN-main\visualizer_drag.py", line 396, in main
    viz.draw_frame()
  File "C:\Users\alime\Downloads\DragGAN-main1\DragGAN-main\visualizer_drag.py", line 181, in draw_frame
    h, w, _ = self.result.image.shape
  File "C:\Users\alime\Downloads\DragGAN-main1\DragGAN-main\dnnlib\util.py", line 47, in __getattr__
    raise AttributeError(name)
AttributeError: image

**Comment by alimehdi242** [comment]
I am using windows 11

**Comment by Aquahugs** [comment]
I am also running into this error. App loads but everything else crashes and throws this error once you try to add an image or load any of the models from recent.

**Comment by PDillis** [comment]
Honestly, I found that removing that part of the code made it work. I'm guessing there's something missing/bug in the code, but in the meantime, removing these 3 lines lets you at least run the GUI locally (you won't be able to use the mask though):

These are lines 180-182 of `visualizer_drag.py`, so comment them out or something:
```py
# if self.check_update_mask(**self.args):
#             h, w, _ = self.result.image.shape
#             self.drag_widget.init_mask(w, h)
```

**Comment by PDillis** [comment]
Update: the PR ccd84ff has fixed this, so just do a git pull and the error shouldn't exist.
