### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='

### ISSUE THREAD

**Issue by vygas2121** [XingangPan/DragGAN#396]

**Comment by christopherquenneville** [comment]
To run this software you need to do the following in Anaconda:

cd C:\Machine Learning\GAN\DragGAN\DragCAN (replace with your path)
conda activate stylegan3
.\scripts\gui.bat

You probably forgot to activate the venv.

**Comment by LeoZeda** [comment]
> No CUDA runtime is found, using CUDA_HOME='B:\Program Files\NvidiaGPU Computing Toolkit\cuda\v11.8' Traceback (most recent call last): File "B:\dragengen\DragGAN\visualizer_drag.py", line 403, in main() File "B:\Users\vygas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in **call** return self.main(*args, **kwargs) File "B:\Users\vygas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main rv = self.invoke(ctx) File "B:\Users\vygas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "B:\Users\vygas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke return __callback(*args, **kwargs) File "B:\dragengen\DragGAN\visualizer_drag.py", line 397, in main viz.draw_frame() File "B:\dragengen\DragGAN\visualizer_drag.py", line 168, in draw_frame self._async_renderer.set_args(**self.args) File "B:\dragengen\DragGAN\visualizer_drag.py", line 295, in set_args self._set_args_sync(**args) File "B:\dragengen\DragGAN\visualizer_drag.py", line 312, in _set_args_sync self._renderer_obj = renderer.Renderer() File "B:\dragengen\DragGAN\viz\renderer.py", line 80, in **init** self._start_event = torch.cuda.Event(enable_timing=True) File "B:\Users\vygas\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\streams.py", line 164, in **new** return super(Event, cls).**new**( File "B:\Users\vygas\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda_utils.py", line 46, in err_fn raise RuntimeError( RuntimeError: Tried to instantiate dummy base class Event Press any key to continue . . .


I'm facing the same problem. Did you solve it？  @vygas2121

**Comment by hitzhangjie** [comment]
Maybe you forget run `conda activate stylegan3` ?
