### ISSUE TITLE
OSError: exception: access violation reading 0x0000000000000330

### ISSUE THREAD

**Issue by Colin-Jing** [XingangPan/DragGAN#398]
Has anyone encountered the same problem? I tried cuda version 12 and 11, but the following error was reported:

C:\Users\tanjing\.conda\envs\DragGAN\lib\site-packages\glfw\__init__.py:916: GLFWError: (65542) b'WGL: The driver does not appear to support OpenGL'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "F:\tanjing\my_project\BaiduSyncdisk\my_project\DragGAN-main\visualizer_drag.py", line 403, in <module>
    main()
  File "C:\Users\tanjing\.conda\envs\DragGAN\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\tanjing\.conda\envs\DragGAN\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\tanjing\.conda\envs\DragGAN\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\tanjing\.conda\envs\DragGAN\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "F:\tanjing\my_project\BaiduSyncdisk\my_project\DragGAN-main\visualizer_drag.py", line 362, in main
    viz = Visualizer(capture_dir=capture_dir)
  File "F:\tanjing\my_project\BaiduSyncdisk\my_project\DragGAN-main\visualizer_drag.py", line 31, in __init__
    super().__init__(title='DragGAN', window_width=3840, window_height=2160)
  File "F:\tanjing\my_project\BaiduSyncdisk\my_project\DragGAN-main\gui_utils\imgui_window.py", line 24, in __init__
    super().__init__(title=title, **glfw_kwargs)
  File "F:\tanjing\my_project\BaiduSyncdisk\my_project\DragGAN-main\gui_utils\glfw_window.py", line 36, in __init__
    self._attach_glfw_callbacks()
  File "F:\tanjing\my_project\BaiduSyncdisk\my_project\DragGAN-main\gui_utils\glfw_window.py", line 219, in _attach_glfw_callbacks
    glfw.set_key_callback(self._glfw_window, self._glfw_key_callback)
  File "C:\Users\tanjing\.conda\envs\DragGAN\lib\site-packages\glfw\__init__.py", line 1995, in set_key_callback
    _glfw.glfwSetKeyCallback(window, cbfun)
OSError: exception: access violation reading 0x0000000000000330

**Comment by BlackShao123** [comment]
do you solve it? i have the same case
