### ISSUE TITLE
python visualizer_drag_gradio.py issue

### ISSUE THREAD

**Issue by Sergiu1002** [XingangPan/DragGAN#399]
python visualizer_drag_gradio.py
File under cache_dir (./checkpoints):
['stylegan2-afhqcat-512x512.pkl', 'stylegan2-car-config-f.pkl', 'stylegan2-cat-config-f.pkl', 'stylegan2-ffhq-512x512.pkl', 'stylegan2_dogs_1024_pytorch.pkl', 'stylegan2_elephants_512_pytorch.pkl', 'stylegan2_horses_256_pytorch.pkl', 'stylegan2_lions_512_pytorch.pkl']
Valid checkpoint file:
{'stylegan2-afhqcat-512x512': './checkpoints\\stylegan2-afhqcat-512x512.pkl', 'stylegan2-car-config-f': './checkpoints\\stylegan2-car-config-f.pkl', 'stylegan2-cat-config-f': './checkpoints\\stylegan2-cat-config-f.pkl', 'stylegan2-ffhq-512x512': './checkpoints\\stylegan2-ffhq-512x512.pkl', 'stylegan2_dogs_1024_pytorch': './checkpoints\\stylegan2_dogs_1024_pytorch.pkl', 'stylegan2_elephants_512_pytorch': './checkpoints\\stylegan2_elephants_512_pytorch.pkl', 'stylegan2_horses_256_pytorch': './checkpoints\\stylegan2_horses_256_pytorch.pkl', 'stylegan2_lions_512_pytorch': './checkpoints\\stylegan2_lions_512_pytorch.pkl'}
Loading "./checkpoints\stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Traceback (most recent call last):
  File "C:\Users\Desktop\DragGAN\visualizer_drag_gradio.py", line 205, in <module>
    global_state = init_images(global_state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\DragGAN\visualizer_drag_gradio.py", line 96, in init_images
    add_watermark_np(np.array(init_image)))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\DragGAN\viz\renderer.py", line 56, in add_watermark_np
    text_width, text_height = font.getsize(watermark_text)
                              ^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

**Comment by danielchan-25** [comment]
I have also encountered this problem. Do you have a solution?

**Comment by BalaMurugan171103** [comment]
try pip install Pillow<=9.5.0
