### ISSUE TITLE
AssertionError:  does not exist!

### ISSUE THREAD

**Issue by IssacCzy** [XingangPan/DragGAN#467]
**two questions:**
* 1、the btn [Path to latent code] is unusable，cannot be clicked，it's a small problem.
* 2、when i click the btn: [Load latent]，i got the exception 

```
D:\ProgramData\anaconda3\envs\DragGAN\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "D:\Projects\DragGAN\visualizer_drag.py", line 403, in <module>
    main()
  File "D:\ProgramData\anaconda3\envs\DragGAN\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\DragGAN\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\DragGAN\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\DragGAN\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\DragGAN\visualizer_drag.py", line 397, in main
    viz.draw_frame()
  File "D:\Projects\DragGAN\visualizer_drag.py", line 156, in draw_frame
    self.latent_widget(expanded)
  File "D:\Projects\DragGAN\gui_utils\imgui_utils.py", line 83, in decorator
    res = method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\DragGAN\viz\latent_widget.py", line 57, in __call__
    assert os.path.isfile(self.w_path), f"{self.w_path} does not exist!"
AssertionError:  does not exist!
```
![image](https://github.com/XingangPan/DragGAN/assets/17309821/f8e80ac8-2c63-4a08-a235-ff78647c33f8)

![image](https://github.com/XingangPan/DragGAN/assets/17309821/c6d121ee-6684-4bf4-a71c-7a5761155c4b)

do you konw how to fix it ?  teach me, 3Q !

**Comment by edrees2022** [comment]
Same issue

**Comment by edrees2022** [comment]
The [Path to latent code] field is where you should input the file path of your latent code as a string. Once you’ve filled in this field, you will be able to click the button. I hope this helps you!
