### ISSUE TITLE
docker is not updated ? A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0 as it may crash. To support both 1.x and 2.x

### ISSUE THREAD

**Issue by yoni333** [XingangPan/DragGAN#469]
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/workspace/src/visualizer_drag_gradio.py", line 15, in <module>
    from viz.renderer import Renderer, add_watermark_np

**Comment by inging-ing** [comment]
> A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2.
> 
> Traceback (most recent call last): File "/workspace/src/visualizer_drag_gradio.py", line 15, in from viz.renderer import Renderer, add_watermark_np

I'm also having this issue, did anyone solve it?
