### ISSUE TITLE
KeyError: 'stylegan_human_v2_512'

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [XingangPan/DragGAN#55]
Simply running 

```python
python visualizer_drag_gradio.py
```

after the download script results in

```
(.venv) ➜  DragGAN git:(main) python visualizer_drag_gradio.py

File under cache_dir (./checkpoints):
['stylegan2_horses_256_pytorch.pkl', 'stylegan2_lions_512_pytorch.pkl', 'stylegan2-ffhq-512x512.pkl', 'stylegan2-car-config-f.pkl', 'stylegan2-cat-config-f.pkl', 'stylegan2_elephants_512_pytorch.pkl', 'stylegan2_dogs_1024_pytorch.pkl', 'stylegan2-afhqcat-512x512.pkl']
Valid checkpoint file:
{'stylegan2_horses_256_pytorch': './checkpoints/stylegan2_horses_256_pytorch.pkl', 'stylegan2_lions_512_pytorch': './checkpoints/stylegan2_lions_512_pytorch.pkl', 'stylegan2-ffhq-512x512': './checkpoints/stylegan2-ffhq-512x512.pkl', 'stylegan2-car-config-f': './checkpoints/stylegan2-car-config-f.pkl', 'stylegan2-cat-config-f': './checkpoints/stylegan2-cat-config-f.pkl', 'stylegan2_elephants_512_pytorch': './checkpoints/stylegan2_elephants_512_pytorch.pkl', 'stylegan2_dogs_1024_pytorch': './checkpoints/stylegan2_dogs_1024_pytorch.pkl', 'stylegan2-afhqcat-512x512': './checkpoints/stylegan2-afhqcat-512x512.pkl'}
Traceback (most recent call last):
  File "/home/zuppif/Documents/DragGAN/visualizer_drag_gradio.py", line 200, in <module>
    global_state = init_images(global_state)
  File "/home/zuppif/Documents/DragGAN/visualizer_drag_gradio.py", line 72, in init_images
    valid_checkpoints_dict[state['pretrained_weight']],  # pkl
KeyError: 'stylegan_human_v2_512'
```

Thanks a lot!

**Comment by FrancescoSaverioZuppichini** [comment]
Download this file, idk what it is 

https://huggingface.co/turx2/eargx/blob/main/stylegan_human_v2_512.pkl

**Comment by FrancescoSaverioZuppichini** [comment]
I am not sure if this is suppose to be included in the download script file, happy to make a PR about it but it would probably be best if the authors hosted somewhere else instead of relying to a third party repo. I am not sure here, looking for guidance

**Comment by FrancescoSaverioZuppichini** [comment]
It was! you can get it from -> https://drive.google.com/file/d/1dlFEHbu-WzQWJl7nBBZYcTyo000H9hVm/view

however it may be also great to have a direct link -> closing now
