### ISSUE TITLE
App crashes right after opening GUI

### ISSUE THREAD

**Issue by enriquemorenotent** [XingangPan/DragGAN#57]
This is the output I get, after failing to boot up the GUI.

```
DragGAN on  main via 🅒 stylegan3 took 32s 
➜ sh scripts/gui.sh
/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Loading "/home/dbugger/projects/ai/DragGAN/checkpoints/stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Failed!

Traceback (most recent call last):
  File "/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dbugger/projects/ai/DragGAN/viz/renderer.py", line 111, in render
    self.init_network(res, **args)
  File "/home/dbugger/projects/ai/DragGAN/viz/renderer.py", line 248, in init_network
    w = G.mapping(z, label, truncation_psi=trunc_psi, truncation_cutoff=trunc_cutoff)
  File "/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dbugger/projects/ai/DragGAN/training/networks_stylegan2.py", line 247, in forward
    x = layer(x)
  File "/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dbugger/projects/ai/DragGAN/training/networks_stylegan2.py", line 125, in forward
    x = bias_act.bias_act(x, b, act=self.activation)
  File "/home/dbugger/projects/ai/DragGAN/torch_utils/ops/bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "/home/dbugger/projects/ai/DragGAN/torch_utils/ops/bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
  File "/home/dbugger/projects/ai/DragGAN/torch_utils/custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/2] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/include -isystem /home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/include/TH -isystem /home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/include/THC -isystem /home/dbugger/anaconda3/envs/stylegan3/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++17 -c /home/dbugger/.cache/torch_extensions/py39_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-3060/bias_act.cu -o bias_act.cuda.o 
FAILED: bias_act.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/include -isystem /home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/include/TH -isystem /home/dbugger/anaconda3/envs/stylegan3/lib/python3.9/site-packages/torch/include/THC -isystem /home/dbugger/anaconda3/envs/stylegan3/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++17 -c /home/dbugger/.cache/torch_extensions/py39_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-3060/bias_act.cu -o bias_act.cuda.o 
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
ninja: build stopped: subcommand failed.
```

**Comment by nbollman** [comment]
Diddo here, Ubuntu 22.04, RTX 3090

(draggan) jon@the-wall:~/ai/DragGAN$ sh scripts/gui.sh
Loading "/home/jon/ai/DragGAN/checkpoints/stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Failed!

Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/jon/miniconda3/envs/draggan/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jon/ai/DragGAN/viz/renderer.py", line 112, in render
    self.init_network(res, **args)
  File "/home/jon/ai/DragGAN/viz/renderer.py", line 249, in init_network
    w = G.mapping(z, label, truncation_psi=trunc_psi, truncation_cutoff=trunc_cutoff)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jon/ai/DragGAN/training/networks_stylegan2.py", line 247, in forward
    x = layer(x)
        ^^^^^^^^
  File "/home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jon/ai/DragGAN/training/networks_stylegan2.py", line 125, in forward
    x = bias_act.bias_act(x, b, act=self.activation)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jon/ai/DragGAN/torch_utils/ops/bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
                                                      ^^^^^^^
  File "/home/jon/ai/DragGAN/torch_utils/ops/bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jon/ai/DragGAN/torch_utils/custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "/home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/3] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/TH -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/THC -isystem /home/jon/miniconda3/envs/draggan/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++17 -c /home/jon/.cache/torch_extensions/py311_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-3090/bias_act.cu -o bias_act.cuda.o 
FAILED: bias_act.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/TH -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/THC -isystem /home/jon/miniconda3/envs/draggan/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++17 -c /home/jon/.cache/torch_extensions/py311_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-3090/bias_act.cu -o bias_act.cuda.o 
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[2/3] c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/TH -isystem /home/jon/miniconda3/envs/draggan/lib/python3.11/site-packages/torch/include/THC -isystem /home/jon/miniconda3/envs/draggan/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /home/jon/.cache/torch_extensions/py311_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-3090/bias_act.cpp -o bias_act.o 
ninja: build stopped: subcommand failed.

**Comment by Tany-g** [comment]
Have you solved it? I had the same problem,Ubuntu 22.04 ,RTX3090
(stylegan3) tt@ubuntu:~/Desktop/Tany/DragGAN$ bash scripts/gui.sh 
Loading "/home/tt/Desktop/Tany/DragGAN/checkpoints/stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Failed!

Traceback (most recent call last):
  File "/home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/tt/.conda/envs/stylegan3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tt/Desktop/Tany/DragGAN/viz/renderer.py", line 112, in render
    self.init_network(res, **args)
  File "/home/tt/Desktop/Tany/DragGAN/viz/renderer.py", line 249, in init_network
    w = G.mapping(z, label, truncation_psi=trunc_psi, truncation_cutoff=trunc_cutoff)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/Desktop/Tany/DragGAN/training/networks_stylegan2.py", line 247, in forward
    x = layer(x)
        ^^^^^^^^
  File "/home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/Desktop/Tany/DragGAN/training/networks_stylegan2.py", line 125, in forward
    x = bias_act.bias_act(x, b, act=self.activation)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/Desktop/Tany/DragGAN/torch_utils/ops/bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
                                                      ^^^^^^^
  File "/home/tt/Desktop/Tany/DragGAN/torch_utils/ops/bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/Desktop/Tany/DragGAN/torch_utils/custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "/home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/2] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/include -isystem /home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/include/TH -isystem /home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/include/THC -isystem /home/tt/.conda/envs/stylegan3/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++17 -c /home/tt/.cache/torch_extensions/py311_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-3090/bias_act.cu -o bias_act.cuda.o 
FAILED: bias_act.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/include -isystem /home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/include/TH -isystem /home/tt/.conda/envs/stylegan3/lib/python3.11/site-packages/torch/include/THC -isystem /home/tt/.conda/envs/stylegan3/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++17 -c /home/tt/.cache/torch_extensions/py311_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-3090/bias_act.cu -o bias_act.cuda.o 
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
ninja: build stopped: subcommand failed.

**Comment by enriquemorenotent** [comment]
No, problem persists
