### ISSUE TITLE
Crush When I drag the pic to the app

### ISSUE THREAD

**Issue by Uknownoth1ng** [XingangPan/DragGAN#59]
Traceback (most recent call last):
  File "D:\AI\DragGAN\DragGAN-main\DragGAN-main\visualizer_drag.py", line 402, in <module>
    main()
  File "C:\Users\vip\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vip\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\vip\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vip\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\AI\DragGAN\DragGAN-main\DragGAN-main\visualizer_drag.py", line 396, in main
    viz.draw_frame()
  File "D:\AI\DragGAN\DragGAN-main\DragGAN-main\visualizer_drag.py", line 181, in draw_frame
    h, w, _ = self.result.image.shape
  File "D:\AI\DragGAN\DragGAN-main\DragGAN-main\dnnlib\util.py", line 47, in __getattr__
    raise AttributeError(name)
AttributeError: image

when I try to drag a pic to the pic....
and show me 'no network pickle loaded' 
-

想上传自己的图进行编辑，拖了张图去中间，瞬间程序闪退，显示no network pickle loaded

**Comment by PDillis** [comment]
Comment out those 3 lines of code and it should run, that's my fix for now.

**Comment by lauchokyip** [comment]
@PDillis would you mind sharing which 3 lines of code did you comment out? thanks!

**Comment by lauchokyip** [comment]
Please check your `checkpoints` directory,  as the README mentioned
> This GUI supports editing GAN-generated images. 
The fastest way to test is is to just download the premodel

```bash
sh scripts/gui.sh
```
