### ISSUE TITLE
UnboundLocalError: local variable 'reset' referenced before assignment

### ISSUE THREAD

**Issue by belalesawe** [XingangPan/DragGAN#78]
In the GUI, if you try to minimize the "Drag" button, it will return UnboundLocalError. To reproduce just run the gui.sh script and try to minimize the "Drag" button.
`py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Loading "/home/belal/personal/DragGAN/checkpoints/stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Traceback (most recent call last):
  File "/home/belal/personal/DragGAN/visualizer_drag.py", line 402, in <module>
    main()
  File "/home/belal/anaconda3/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/belal/anaconda3/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/belal/anaconda3/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/belal/anaconda3/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/belal/personal/DragGAN/visualizer_drag.py", line 396, in main
    viz.draw_frame()
  File "/home/belal/personal/DragGAN/visualizer_drag.py", line 158, in draw_frame
    self.drag_widget(expanded)
  File "/home/belal/personal/DragGAN/gui_utils/imgui_utils.py", line 83, in decorator
    res = method(self, *args, **kwargs)
  File "/home/belal/personal/DragGAN/viz/drag_widget.py", line 164, in __call__
    viz.args.reset = reset
UnboundLocalError: local variable 'reset' referenced before assignment
`

**Comment by Peter-D-James** [comment]
The same error
