### ISSUE TITLE
Setting up PyTorch plugin "bias_act_plugin"... Failed!

### ISSUE THREAD

**Issue by wangwenqiao666** [XingangPan/DragGAN#90]
when I run python visualizer_drag_gradio.py, some error occurred:
Setting up PyTorch plugin "bias_act_plugin"... Failed!
Traceback (most recent call last):
  File "/data/DragGAN/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/sh/miniconda3/envs/webui/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/DragGAN/drag.py", line 200, in <module>
    global_state = init_images(global_state)
  File "/data/DragGAN/drag.py", line 70, in init_images
    state['renderer'].init_network(
  File "/data/DragGAN/viz/renderer.py", line 248, in init_network
    w = G.mapping(z, label, truncation_psi=trunc_psi, truncation_cutoff=trunc_cutoff)
  File "/data/DragGAN/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/DragGAN/training/networks_stylegan2.py", line 247, in forward
    x = layer(x)
  File "/data/DragGAN/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/DragGAN/training/networks_stylegan2.py", line 125, in forward
    x = bias_act.bias_act(x, b, act=self.activation)
  File "/data/DragGAN/torch_utils/ops/bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "/data/DragGAN/torch_utils/ops/bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
  File "/data/DragGAN/torch_utils/custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "/data/DragGAN/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/data/DragGAN/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/data/DragGAN/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/data/DragGAN/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/3] /usr/local/cuda/bin/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/TH -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/bin/include -isystem /home/sh/miniconda3/envs/webui/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++17 -c /home/sh/.cache/torch_extensions/py310_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-4090/bias_act.cu -o bias_act.cuda.o 
FAILED: bias_act.cuda.o 
/usr/local/cuda/bin/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/TH -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/bin/include -isystem /home/sh/miniconda3/envs/webui/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++17 -c /home/sh/.cache/torch_extensions/py310_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-4090/bias_act.cu -o bias_act.cuda.o 
/bin/sh: 1: /usr/local/cuda/bin/bin/nvcc: Permission denied
[2/3] c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/TH -isystem /data/DragGAN/venv/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/bin/include -isystem /home/sh/miniconda3/envs/webui/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /home/sh/.cache/torch_extensions/py310_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-nvidia-geforce-rtx-4090/bias_act.cpp -o bias_act.o 
ninja: build stopped: subcommand failed.

**Comment by wangwenqiao666** [comment]
ubuntu20.04
rtx4090
torch2.0
cuda11.7

**Comment by FrancescoSaverioZuppichini** [comment]
how are you installing everything? What is your nvidia-smi output? Try with

```
conda env create python=3.7 -f environment.yml
conda activate stylegan3
```
Then install the additional requirements

```
pip install -r requirements
```

**Comment by gonduras** [comment]
same for me

(venv) E:\DragGAN>call gui.bat
Already up to date.
Loading "E:\DragGAN\checkpoints\stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Failed!

Traceback (most recent call last):
  File "E:\DragGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "C:\Users\gonduras\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\DragGAN\viz\renderer.py", line 112, in render
    self.init_network(res, **args)
  File "E:\DragGAN\viz\renderer.py", line 249, in init_network
    w = G.mapping(z, label, truncation_psi=trunc_psi, truncation_cutoff=trunc_cutoff)
  File "E:\DragGAN\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\DragGAN\training\networks_stylegan2.py", line 247, in forward
    x = layer(x)
  File "E:\DragGAN\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\DragGAN\training\networks_stylegan2.py", line 125, in forward
    x = bias_act.bias_act(x, b, act=self.activation)
  File "E:\DragGAN\torch_utils\ops\bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "E:\DragGAN\torch_utils\ops\bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
  File "E:\DragGAN\torch_utils\custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "E:\DragGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "E:\DragGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\DragGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "E:\DragGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/1] "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64/link.exe" bias_act.o bias_act.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:E:\DragGAN\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:E:\DragGAN\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:bias_act_plugin.pyd
FAILED: bias_act_plugin.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64/link.exe" bias_act.o bias_act.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:E:\DragGAN\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:E:\DragGAN\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:bias_act_plugin.pyd
LINK : fatal error LNK1104: cannot open file 'python310.lib'
ninja: build stopped: subcommand failed.

**Comment by gonduras** [comment]
ok solved it.
you should do one of two things:
1. set PYTHONPATH=C:\Users\***\AppData\Local\Programs\Python\Python310\libs (or where your phyton installed)
2. copy the content of Python310\libs folder to venv\scripts\libs


E:\DragGAN\venv\Scripts>activate

(venv) E:\DragGAN\venv\Scripts>set PYTHONPATH=C:\Users\gonduras\AppData\Local\Programs\Python\Python310\libs

(venv) E:\DragGAN\venv\Scripts>cd..

(venv) E:\DragGAN\venv>cd..

(venv) E:\DragGAN>call gui.bat
Already up to date.
Loading "E:\DragGAN\checkpoints\stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.

**Comment by whateverThisIs** [comment]
> how are you installing everything? What is your nvidia-smi output? Try with
> 
> ```
> conda env create python=3.7 -f environment.yml
> conda activate stylegan3
> ```
> 
> Then install the additional requirements
> 
> ```
> pip install -r requirements
> ```

I got the same issue when I followed instruction from NVlabs/stylegan3.

However if I simply install as you suggested, my conda just takes forever to solve the environment...

Could we just have a really easy installation for windows? Thx.

**Comment by uuunaja** [comment]
> > how are you installing everything? What is your nvidia-smi output? Try with
> > ```
> > conda env create python=3.7 -f environment.yml
> > conda activate stylegan3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then install the additional requirements
> > ```
> > pip install -r requirements
> > ```
> 
> I got the same issue when I followed instruction from NVlabs/stylegan3.
> 
> However if I simply install as you suggested, my conda just takes forever to solve the environment...
> 
> Could we just have a really easy installation for windows? Thx.

I'm on Window user, and I have the same problem as you

**Comment by marianbastiUNRN** [comment]
Found a related fix on the [stylegan repo](https://github.com/rosinality/stylegan2-pytorch/issues/325), worked for me!

**Comment by Vadim2S** [comment]
There TWO possible roots of evil. Eliminate both:
1) Install CUDA version > 11.6
2) Use marianbastiUNRN (thanks!) solution with python310.lib

**Comment by hitzhangjie** [comment]
same for me, see also: https://github.com/XingangPan/DragGAN/issues/406

**Comment by hitzhangjie** [comment]
> There TWO possible roots of evil. Eliminate both:
> 
> 1. Install CUDA version > 11.6
> 2. Use marianbastiUNRN (thanks!) solution with python310.lib

I install cuda v11.7, it still failed. see: https://github.com/XingangPan/DragGAN/issues/406
